### ISSUE TITLE
[meta] Aplicar o tema do CPA no EJ

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#159]
A arquitetura de temas foi documentada na issue #158. Protótipo no invision: https://projects.invisionapp.com/d/main#/projects/prototypes/14015249

Para simplificar, vamos trabalhar apenas na lógica deslogado e logado CPA. Nesse momento, qq usuário logado será usuário CPA.

**Priorização das telas:**
- [x] [Tela de login](https://projects.invisionapp.com/d/main#/console/14015249/302157265/preview) - issue #175 com @lucasssm 
- [x] [Home deslogades](https://projects.invisionapp.com/d/main#/console/14015249/302157283/preview) (deve aparecer para todo usuário deslogado) e [home logada CPA](https://projects.invisionapp.com/d/main#/console/14015249/302157282/preview) - issue #176 com @caiosba 
- [x] [Menu deslogado](https://projects.invisionapp.com/d/main#/console/14015249/302157271/preview) e [menu logado CPA](https://projects.invisionapp.com/d/main#/console/14015249/302157277/comments) - issue #177 com @lucasssm 
- [x] Tela de perfil: (i) [User ainda não comentou](https://projects.invisionapp.com/d/main#/console/14015249/302157269/preview), (ii) [User comentou](https://projects.invisionapp.com/d/main#/console/14015249/302157268/preview), (iii) [Visualização de trofeus](https://projects.invisionapp.com/d/main#/console/14015249/302157266/preview), (iv) [Visualização de contribuições](https://projects.invisionapp.com/d/main#/console/14015249/302157267/preview) - issue #178 com @lucasssm 
- [x] Lista de conversas: (i) [deslogado](https://projects.invisionapp.com/d/main#/console/14015249/302157273/preview), (ii) [logado CPA conversas públicas](https://projects.invisionapp.com/d/main#/console/14015249/302157276/preview), (iii) [logado CPA minhas conversas](https://projects.invisionapp.com/d/main#/console/14015249/302157272/preview) (ocultando o botão de adicionar conversa), (iv) [timeline de conversas de um usuário especifico](https://projects.invisionapp.com/d/main#/console/14015249/302157274/preview) (acessível via /\<username\>) - issue #179 com @caiosba 
- [x] Internas de conversa [user deslogado](https://projects.invisionapp.com/d/main#/console/14015249/302157279/preview) e [user logado CPA](https://projects.invisionapp.com/d/main#/console/14015249/302157278/preview) (ignorando por agora os botões de edição e solicitar relatório do header) - issue #180 com @caiosba

**Comment by caiosba** [comment]
Tarefas relacionadas concluídas.
