### ISSUE TITLE
Meta Back

### ISSUE THREAD

**Issue by fabiommendes** [ejplatform/ej-server#237]
* [ ] Framework de criação de fixtures para testes
* [ ] Testes unitários
* [ ] Framework de tasks
* [ ] Clusterização e ML assíncrona
* [ ] Eliminar erros em análise estática

**Comment by ricardopoppi** [comment]
deprecated
