### ISSUE TITLE
Meta Front

### ISSUE THREAD

**Issue by fabiommendes** [ejplatform/ej-server#238]
* [ ] Estrutura de temas
* [x] Acessibilidade
* [ ] Testes das views
* [ ] Testes de integração com o splinter
* [ ] PWA
* [ ] Visualização dos clusters com paper.js
* [ ] Relatórios com echarts

**Comment by ricardopoppi** [comment]
deprecated
