### ISSUE TITLE
[META] Issues da v2 da gamificação

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#392]
@BrunaNayara essa issue meta é um bom lugar pra gente criar as tarefas para implementação da v2 da gamificação, já que começaremos por ela.

- [x] Desenho dos wireframes (#391)
- [x] Definição dos dados que devem ser gerados pelo back/ml para atender a necessidade de identificação dos perfis (detalhes no corpo da issue #391)
(talvez essa ultima tarefa deva ser desmembrada por tipo de dado @BrunaNayara)
- [ ] Identificar participante mais próximo da borda entre dois clusters (#395)
- [x] Criar grupos de Ponte de diálogo (#396)
- [x] Criar grupos de cada cluster da conversa #397
- [ ] Criar mecanismo de notificação de gamificação (#398)

**Comment by ricardopoppi** [comment]
fechando essa pois as issues correspondentes já estão sendo monitoradas como parte da release Barbara  Liskov
