### ISSUE TITLE
[meta] Integração do módulo matemático no EJ

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#61]
Integração do math no EJplatform
Quem: @fabiommendes  passando o bastão pro @luanguimaraesla 

Checklist:
- [x] Desenvolver o app EJ-cluster onde são registradas as models de cluster e estereótipos (organizar em arquitetura fácil de evoluir) - issue #80
- [x] Ativar clusterização dumb - issue #81
- [x] Amadurecer o app EJ-cluster para machine learning (melhorar os algoritmos) - issue #82
- [x] Ativar biblioteca ou App que expõe um Pandas Dataframe (Gráficos do MatPlotLib / HTML - pesquisar MPL D3) - issue #83
