### ISSUE TITLE
[meta] Melhorias na interface atual da plataforma do CPA

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#63]
Melhorias na interface atual da plataforma do CPA
Quem: @ricardopoppi e @parrahenri validando e homologando

Checklist:

- [x] Customizar a idv do CPA para uso na PVPA  - issue #75 
- [x] Criar os wireframes/layout usando a idv do CPA - issue #77 
- [ ] Rodar um checklist na interface atual do PVPA, procurando por elementos faltantes e erros de UX - issue #76

**Comment by ricardopoppi** [comment]
Fechando essa issue pois o diagnóstico de usabilidade será feito no contexto do genérico
