### ISSUE TITLE
[meta] Bugs do ultimo merge

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#636]
- [ ] Na versão responsiva, item de menu hamburguer "conversa" não expande

- [ ] Estilos estranhos, fontes em vermelho, na interna da conversa

![captura de tela de 2018-11-14 00-53-13](https://user-images.githubusercontent.com/1162183/48457245-1570bf80-e7a9-11e8-8a85-01839409ee11.png)

- [ ] Estilos estranhos que apagam o texto no form de novo comentário

![captura de tela de 2018-11-14 00-53-23](https://user-images.githubusercontent.com/1162183/48457256-1e619100-e7a9-11e8-9710-e2bbb25415e8.png)

- [ ] Quando o usuário já fez os 2 comentários que tem direito, a msg é incorreta (é como se o usuário não estivesse logado)
@fabiolamfleury pode olhar esse aqui?

![captura de tela de 2018-11-14 01-00-09](https://user-images.githubusercontent.com/1162183/48457266-33d6bb00-e7a9-11e8-96ba-d4514d606d0a.png)

**Comment by pablodiegoss** [comment]
O @LeoSilvaGomes começou a investigação e correção destes bugs na branch de refactor css, issue #514
