### ISSUE TITLE
[meta] Gameficação do EJ

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#66]
Criar a gameficação do EJ

Checklist:
- [ ] Finalizar o documento da proposta no formato GDD - issue #65 
- [x] Oficina com a equipe (02/jul)
- [ ] Pesquisar ux de gamificação produzindo recomendações - (ainda não criada)

**Comment by ricardopoppi** [comment]
Fechando essa issue pois deprecou. Gamificação está sendo realizada na issue #227
