### ISSUE TITLE
[meta] Integração do RocketChat

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#71]
[meta] Integração do RocketChat
Quem: @leandronunes puxando essa

- [x]  Customização do Rocketchat com a idv genérica EJ seguindo a arquitetura de css do EJ - issue #33
- [ ] Checklist de problemas de UX na integração - issue #73 
- [x] Aplicar no rocket a idv do CPA - issue #74
