### ISSUE TITLE
[meta] Implementação do front genérico do EJ

### ISSUE THREAD

**Issue by ricardopoppi** [ejplatform/ej-server#72]
Implementação do front genérico do EJ
Quem: @fabiommendes  passando o bastão pro @caiosba e @lucasssm (e @leandronunes colando junto após o #rocket)

Checklist:
- [x] Decisão sobre a tecnologia de frontend - issue #64 
- [ ] Reorganizar as views nos apps corretos do django - issue #84
- [ ] Criar o esqueleto navegável com base no mapa de interação - issue #85
- [ ] Implementação dos wireframes genéricos - issue #78
